### ISSUE TITLE
Not listed in addon manager: add content to package.xml

### ISSUE THREAD

**Issue by d1nuc0m** [mnesarco/FreeCAD_Utils#5]
Hi, actually this addon is not shown in FreeCAD's Addon Manager, even if linked by the [FreeCAD-addons repository](https://github.com/FreeCAD/FreeCAD-addons), as the mandatory `content` section of package.xml is practically empty:
```
    <content>
        <!-- No Workbench or macros. This package contains some functions and general utilities -->
    </content>
```
So when opening the addon manager, FC's console reports `Package MnesarcoUtils does not list any content items in its package.xml metadata file.`, could you add a [properly formatted/populated content section](https://wiki.freecadweb.org/Package_Metadata#.3Ccontent.3E) to package.xml?

**Comment by mnesarco** [comment]
The package is well formed. There are no workbenches  macros or themes included. What is supposed to declare there in the content section? I think the issue is in the AddonManager because this Addon is valid as it is.

**Comment by mnesarco** [comment]
BTW it is actually listed in the AddonManager:
![image](https://user-images.githubusercontent.com/1087317/206882986-a8e4f865-2014-4f5d-bb58-b178c0833750.png)
