### ISSUE TITLE
Toolbar doesn't remain hiddenif toggled off

### ISSUE THREAD

**Issue by macdroid53** [mnesarco/FreeCAD_Utils#8]
When the mnesarco toolbar is toggled off (right click empty toolbar space and uncheck) the state is not maintained. Restarting FC turns the toolbar back on.

**Comment by macdroid53** [comment]
So the only ways to get it out of my way when I don't need/want it is is to reconfigure Customization or remove the tool with Addon manager?

**Comment by mnesarco** [comment]
Fixed in 5938c139b986325cedd75e8cea99c0891231febc

**Comment by macdroid53** [comment]
This appears to corrected.

**Comment by mnesarco** [comment]
Thank you.

**Comment by macdroid53** [comment]
Sorry, as I use FC the mnesarco toolbar won't stay off...

**Comment by macdroid53** [comment]
Yeah, don't take my last post too seriously. As I can now not reproduce either...
